/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemOrganizer;
import java.awt.Color;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author PC
 */
public class BookOrganizerSystem extends javax.swing.JFrame {

    /**
     * Creates new form BookOrganizerSystem
     */
    public BookOrganizerSystem() {
        initComponents();
        Connect();
        BookOrganizerSystem_Load();
    }

    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    public void Connect() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/Organizer" , "root" , "");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


    }
    
    public void BookOrganizerSystem_Load() {
        
        
       
        
        
        int b;
        
        try {
           ps = con.prepareStatement("select * from System ");
            rs = ps.executeQuery();
            
           ResultSetMetaData rsd = rs.getMetaData();
            
           b = rsd.getColumnCount();
            DefaultTableModel d = (DefaultTableModel)table.getModel();
           d.setRowCount(0);
            
            while(rs.next()) {
                
                Vector vector = new Vector();
                
                for(int i = 1; i<=b; i++) {
                    
                  vector.add(rs.getString("id"));
                   vector.add(rs.getString("title"));
                   vector.add(rs.getString("author"));
                   vector.add(rs.getString("edition"));
                }
                d.addRow(vector);
                
            }
            
                    
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    } 
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textEdition = new javax.swing.JTextField();
        textTitle = new javax.swing.JTextField();
        textAuthor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnRemove1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel.setBackground(java.awt.Color.white);
        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 3));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 20, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 46)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Book Monitoring and Organizer");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 714, 56));

        minimize.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 153, 0));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("_");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, -20, 30, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/symbol.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 90, 90));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/java_coffee.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, 80));

        jPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 120));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Title :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 68, -1));

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Edition :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 68, -1));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Author :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 68, -1));

        textEdition.setBackground(new java.awt.Color(255, 255, 255));
        textEdition.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        textEdition.setForeground(new java.awt.Color(0, 0, 0));
        textEdition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(textEdition, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 250, 50));

        textTitle.setBackground(new java.awt.Color(255, 255, 255));
        textTitle.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        textTitle.setForeground(new java.awt.Color(0, 0, 0));
        textTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(textTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 250, 50));

        textAuthor.setBackground(new java.awt.Color(255, 255, 255));
        textAuthor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        textAuthor.setForeground(new java.awt.Color(0, 0, 0));
        textAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(textAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, 50));

        jPanel3.setBackground(new java.awt.Color(102, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Enter The Book You Want to Barrow Here....");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 320, 30));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/loptop.png"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pc.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 50, 40));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 50, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 50));

        jPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 420, 340));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table.setBackground(new java.awt.Color(153, 153, 255));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        table.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        table.setForeground(new java.awt.Color(0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Title", "Author", "Edition"
            }
        ));
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 860, 480));

        btnUpdate.setBackground(new java.awt.Color(0, 255, 0));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 100, 40));

        btnAdd1.setBackground(new java.awt.Color(0, 204, 204));
        btnAdd1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd1.setText("Add");
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd1MouseExited(evt);
            }
        });
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 100, 40));

        btnConfirm.setBackground(new java.awt.Color(153, 255, 153));
        btnConfirm.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirm.setText("Confirm");
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmMouseExited(evt);
            }
        });
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 100, 40));

        btnRemove1.setBackground(new java.awt.Color(255, 0, 0));
        btnRemove1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRemove1.setForeground(new java.awt.Color(0, 0, 0));
        btnRemove1.setText("Remove");
        btnRemove1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemove1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemove1MouseExited(evt);
            }
        });
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });
        jPanel.add(btnRemove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 100, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/back.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 50, 40));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 50, 40));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/search_1.png"))); // NOI18N
        jPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, 70, 60));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 50, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, 50, 40));
        jPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 486, 50, 50));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/documents.png"))); // NOI18N
        jPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 60, 60));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/remove_1.png"))); // NOI18N
        jPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 60, 60));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/update_1.png"))); // NOI18N
        jPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 80, 70));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/out.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 686, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed

        String titles = textTitle.getText();
        String authors = textAuthor.getText();
        String editions = textEdition.getText();

        try {
            ps = con.prepareStatement("insert into  System(title , author , edition)values(? , ? , ?) ");
            ps.setString(1 , titles);
            ps.setString(2 , authors);
            ps.setString(3, editions);
            int k = ps.executeUpdate();
            
            if(k==1) {
                JOptionPane.showMessageDialog(this, "Books are Added Successfully to our Database");
                
                     textTitle.setText("");
                     textAuthor.setText("");
                     textEdition.setText("");
                     textTitle.requestFocus();
                        BookOrganizerSystem_Load();
                     
                
                
            }
            
            else {
                
                JOptionPane.showMessageDialog(this , "Error");
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
        DefaultTableModel d = (DefaultTableModel)table.getModel();
        int selectIndex = table.getSelectedRow();
        
        int id = Integer.parseInt(d.getValueAt(selectIndex, 0).toString());
        
        textTitle.setText(d.getValueAt(selectIndex, 1).toString());
         textAuthor.setText(d.getValueAt(selectIndex, 2).toString());
          textEdition.setText(d.getValueAt(selectIndex, 3).toString());
        
          
    }//GEN-LAST:event_tableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        
         DefaultTableModel d = (DefaultTableModel)table.getModel();
        int selectIndex = table.getSelectedRow();
        
        int id = Integer.parseInt(d.getValueAt(selectIndex, 0).toString());
        
           String titles = textTitle.getText();
        String authors = textAuthor.getText();
        String editions = textEdition.getText();

        try {
            ps = con.prepareStatement("update System set title = ? , author = ? , edition = ? where id = ? ");
          
            ps.setString(1 , titles);
            ps.setString(2 , authors);
            ps.setString(3, editions);
            ps.setInt(4, id);
            
            int k = ps.executeUpdate();
            
            if(k==1) {
                JOptionPane.showMessageDialog(this, "Books are Updated Successfully");
                
                     textTitle.setText("");
                     textAuthor.setText("");
                     textEdition.setText("");
                     textTitle.requestFocus();
                        BookOrganizerSystem_Load();
                       
                
                
            }
            
            else {
                
                JOptionPane.showMessageDialog(this , "Error");
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
     
        DefaultTableModel d = (DefaultTableModel)table.getModel();
        int selectIndex = table.getSelectedRow();
        
        int id = Integer.parseInt(d.getValueAt(selectIndex, 0).toString());
        
           

        try {
            ps = con.prepareStatement("delete from System where id = ? ");
          
           ;
            ps.setInt(1, id);
            
            int k = ps.executeUpdate();
            
            if(k==1) {
                JOptionPane.showMessageDialog(this, "Books are Removed Successfully");
                
                     textTitle.setText("");
                     textAuthor.setText("");
                     textEdition.setText("");
                     textTitle.requestFocus();
                        BookOrganizerSystem_Load();
                       
                
                
            }
            
            else {
                
                JOptionPane.showMessageDialog(this , "Error");
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnRemove1ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
       
        JOptionPane.showMessageDialog(this , "Thank you ,  your book has been save in our System");
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnAdd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseEntered

        btnAdd1.setBackground(Color.orange);

    }//GEN-LAST:event_btnAdd1MouseEntered

    private void btnAdd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseExited
        btnAdd1.setBackground(Color.cyan);
    }//GEN-LAST:event_btnAdd1MouseExited

    private void btnRemove1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove1MouseEntered
        
         btnRemove1.setBackground(Color.orange);
    }//GEN-LAST:event_btnRemove1MouseEntered

    private void btnRemove1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemove1MouseExited
       
         btnRemove1.setBackground(Color.red);
    }//GEN-LAST:event_btnRemove1MouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
         btnUpdate.setBackground(Color.orange);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
      
         btnUpdate.setBackground(Color.green);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseEntered
        
         btnConfirm.setBackground(Color.orange);
    }//GEN-LAST:event_btnConfirmMouseEntered

    private void btnConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseExited
        
         btnConfirm.setBackground(Color.cyan);
    }//GEN-LAST:event_btnConfirmMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        this.setExtendedState(BookOrganizerSystem.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        TermsCon ts = new TermsCon();
        ts.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        
        JOptionPane.showMessageDialog(this, "Thank you , You can claim your books tommorow" , "Note" , JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookOrganizerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookOrganizerSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTable table;
    private javax.swing.JTextField textAuthor;
    private javax.swing.JTextField textEdition;
    private javax.swing.JTextField textTitle;
    // End of variables declaration//GEN-END:variables
}
