/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemOrganizer;

import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PdfFile extends javax.swing.JFrame {

    /**
     * Creates new form PdfFile
     */
    public PdfFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        view10 = new javax.swing.JButton();
        view1 = new javax.swing.JButton();
        view2 = new javax.swing.JButton();
        view3 = new javax.swing.JButton();
        view4 = new javax.swing.JButton();
        view5 = new javax.swing.JButton();
        view6 = new javax.swing.JButton();
        view7 = new javax.swing.JButton();
        view8 = new javax.swing.JButton();
        view9 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 160, 120));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 120));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, 120));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 160, 120));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 160, 120));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 160, 120));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 120));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 160, 120));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 160, 120));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/pdf.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 160, 120));

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 20, 30));

        minimize.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 0));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("_");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, -20, 20, 60));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Access PDF File here");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 520, 80));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/enter.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 100));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("PD Chapter 10");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 120, 20));

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("PD Chapter 1");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 20));

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("PD Chapter 2");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 120, 20));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("PD Chapter 3");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 120, 20));

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("PD Chapter 4");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 120, 20));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("PD Chapter 5");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 120, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("PD Chapter 6");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 120, 20));

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("PD Chapter 7");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 120, 20));

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("PD Chapter 8");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 120, 20));

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("PD Chapter 9");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 120, 20));

        view10.setBackground(new java.awt.Color(102, 102, 255));
        view10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view10.setForeground(new java.awt.Color(0, 0, 0));
        view10.setText("View");
        view10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view10ActionPerformed(evt);
            }
        });
        jPanel1.add(view10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 100, 40));

        view1.setBackground(new java.awt.Color(102, 102, 255));
        view1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view1.setForeground(new java.awt.Color(0, 0, 0));
        view1.setText("View");
        view1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });
        jPanel1.add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 40));

        view2.setBackground(new java.awt.Color(102, 102, 255));
        view2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view2.setForeground(new java.awt.Color(0, 0, 0));
        view2.setText("View");
        view2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });
        jPanel1.add(view2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 100, 40));

        view3.setBackground(new java.awt.Color(102, 102, 255));
        view3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view3.setForeground(new java.awt.Color(0, 0, 0));
        view3.setText("View");
        view3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view3ActionPerformed(evt);
            }
        });
        jPanel1.add(view3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 100, 40));

        view4.setBackground(new java.awt.Color(102, 102, 255));
        view4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view4.setForeground(new java.awt.Color(0, 0, 0));
        view4.setText("View");
        view4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view4ActionPerformed(evt);
            }
        });
        jPanel1.add(view4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 100, 40));

        view5.setBackground(new java.awt.Color(102, 102, 255));
        view5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view5.setForeground(new java.awt.Color(0, 0, 0));
        view5.setText("View");
        view5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view5ActionPerformed(evt);
            }
        });
        jPanel1.add(view5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 100, 40));

        view6.setBackground(new java.awt.Color(102, 102, 255));
        view6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view6.setForeground(new java.awt.Color(0, 0, 0));
        view6.setText("View");
        view6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view6ActionPerformed(evt);
            }
        });
        jPanel1.add(view6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 100, 40));

        view7.setBackground(new java.awt.Color(102, 102, 255));
        view7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view7.setForeground(new java.awt.Color(0, 0, 0));
        view7.setText("View");
        view7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view7ActionPerformed(evt);
            }
        });
        jPanel1.add(view7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, 100, 40));

        view8.setBackground(new java.awt.Color(102, 102, 255));
        view8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view8.setForeground(new java.awt.Color(0, 0, 0));
        view8.setText("View");
        view8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view8ActionPerformed(evt);
            }
        });
        jPanel1.add(view8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 100, 40));

        view9.setBackground(new java.awt.Color(102, 102, 255));
        view9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        view9.setForeground(new java.awt.Color(0, 0, 0));
        view9.setText("View");
        view9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view9ActionPerformed(evt);
            }
        });
        jPanel1.add(view9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 100, 40));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemOrganizer/image/back.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
      
        this.setExtendedState(PdfFile.ICONIFIED);
        
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
       
        TermsCon tc = new TermsCon();
        tc.setVisible(true);
        this.hide();

    }//GEN-LAST:event_jLabel23MouseClicked

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        
        
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 1.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view1ActionPerformed

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
        
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 2.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view2ActionPerformed

    private void view3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view3ActionPerformed
       
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 3.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view3ActionPerformed

    private void view4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view4ActionPerformed
      
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 4.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view4ActionPerformed

    private void view5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view5ActionPerformed
       
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 5.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view5ActionPerformed

    private void view6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view6ActionPerformed
       
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 6.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view6ActionPerformed

    private void view7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view7ActionPerformed
        
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 7.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view7ActionPerformed

    private void view8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view8ActionPerformed
        
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 8.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view8ActionPerformed

    private void view9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view9ActionPerformed
       
        
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 9.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view9ActionPerformed

    private void view10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view10ActionPerformed
        
          try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 10.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_view10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PdfFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PdfFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PdfFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PdfFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PdfFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton view1;
    private javax.swing.JButton view10;
    private javax.swing.JButton view2;
    private javax.swing.JButton view3;
    private javax.swing.JButton view4;
    private javax.swing.JButton view5;
    private javax.swing.JButton view6;
    private javax.swing.JButton view7;
    private javax.swing.JButton view8;
    private javax.swing.JButton view9;
    // End of variables declaration//GEN-END:variables
}
