/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdf;

import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class pdf extends javax.swing.JFrame {

    /**
     * Creates new form pdf
     */
    public pdf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pd3 = new javax.swing.JButton();
        Pd1 = new javax.swing.JButton();
        pd2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pd3.setBackground(new java.awt.Color(153, 255, 153));
        Pd3.setForeground(new java.awt.Color(0, 0, 0));
        Pd3.setText("PD 3");
        Pd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pd3ActionPerformed(evt);
            }
        });
        jPanel1.add(Pd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, 40));

        Pd1.setBackground(new java.awt.Color(153, 255, 153));
        Pd1.setForeground(new java.awt.Color(0, 0, 0));
        Pd1.setText("PD 1");
        Pd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pd1ActionPerformed(evt);
            }
        });
        jPanel1.add(Pd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 40));

        pd2.setBackground(new java.awt.Color(153, 255, 153));
        pd2.setForeground(new java.awt.Color(0, 0, 0));
        pd2.setText("PD 2");
        pd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd2ActionPerformed(evt);
            }
        });
        jPanel1.add(pd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Pd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pd1ActionPerformed
      
        try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 1.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_Pd1ActionPerformed

    private void Pd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pd3ActionPerformed
       
         try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 3.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_Pd3ActionPerformed

    private void pd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd2ActionPerformed
         try {
            
            File file = new File("C:\\Users\\PC\\Desktop\\PD 2.pdf");
            
            if(file.exists()) {
                
                if(Desktop.isDesktopSupported()) {
                    
                    Desktop.getDesktop().open(file);
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Desktop file are not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "File are not Exist in the System");
            }
        } 
        
        catch (Exception e) {
        }
    }//GEN-LAST:event_pd2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pdf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pd1;
    private javax.swing.JButton Pd3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pd2;
    // End of variables declaration//GEN-END:variables
}
